#include "AbilitySystem/ModMagCalc/MMCMaxMana.h"
#include "AbilitySystem/AuraAttributeSet.h"
#include "Interaction/CombatInterface.h"

UMMCMaxMana::UMMCMaxMana()
{
	this->IntelligenceDef.AttributeToCapture = UAuraAttributeSet::GetIntelligenceAttribute(); // Getter generated by accessor Macro
	this->IntelligenceDef.AttributeSource = EGameplayEffectAttributeCaptureSource::Target;
	// Snapshot = true means that the value is captured when the attribute is created, false means that we get the true value when the effect is applied
	this->IntelligenceDef.bSnapshot = false;

	RelevantAttributesToCapture.Add(this->IntelligenceDef);
}

float UMMCMaxMana::CalculateBaseMagnitude_Implementation(const FGameplayEffectSpec& Spec) const
{
	// Gather tags from source and target
	const FGameplayTagContainer* SourceTags = Spec.CapturedSourceTags.GetAggregatedTags();
	const FGameplayTagContainer* TargetTags = Spec.CapturedTargetTags.GetAggregatedTags();

	FAggregatorEvaluateParameters EvaluationParameters;
	EvaluationParameters.SourceTags = SourceTags;
	EvaluationParameters.TargetTags = TargetTags;

	float Intelligence = 0.f;
	GetCapturedAttributeMagnitude(this->IntelligenceDef, Spec, EvaluationParameters, Intelligence);
	Intelligence = FMath::Max<float>(Intelligence, 0.f);

	int32 PlayerLevel = 1;
	if (Spec.GetContext().GetSourceObject()->Implements<UCombatInterface>())
	{
		PlayerLevel = ICombatInterface::Execute_GetLevel(Spec.GetContext().GetSourceObject());
	}
	return 50.f + 2.f * Intelligence + 15.f * PlayerLevel;
}
