#include "AbilitySystem/ModMagCalc/MMCMaxHealth.h"
#include "AbilitySystem/AuraAttributeSet.h"
#include "Interaction/CombatInterface.h"

UMMCMaxHealth::UMMCMaxHealth()
{
	this->VigorDef.AttributeToCapture = UAuraAttributeSet::GetVigorAttribute(); // Getter generated by accessor Macro
	this->VigorDef.AttributeSource = EGameplayEffectAttributeCaptureSource::Target;
	// Snapshot = true means that the value is captured when the attribute is created, false means that we get the true value when the effect is applied
	this->VigorDef.bSnapshot = false;

	RelevantAttributesToCapture.Add(this->VigorDef);
}

float UMMCMaxHealth::CalculateBaseMagnitude_Implementation(const FGameplayEffectSpec& Spec) const
{
	// Gather tags from source and target
	const FGameplayTagContainer* SourceTags = Spec.CapturedSourceTags.GetAggregatedTags();
	const FGameplayTagContainer* TargetTags = Spec.CapturedTargetTags.GetAggregatedTags();

	FAggregatorEvaluateParameters EvaluationParameters;
	EvaluationParameters.SourceTags = SourceTags;
	EvaluationParameters.TargetTags = TargetTags;

	float Vigor = 0.f;
	GetCapturedAttributeMagnitude(this->VigorDef, Spec, EvaluationParameters, Vigor);
	Vigor = FMath::Max<float>(Vigor, 0.f);

	ICombatInterface* CombatInterface = Cast<ICombatInterface>(Spec.GetContext().GetSourceObject());
	const int32 PlayerLevel = CombatInterface->GetLevel();

	return 80.f + 2.5f * Vigor + 10.f * PlayerLevel;
}
